#!/bin/bash
#jupyter contrib nbextension install --user
#jupyter labextension enable --py widgetslabextension
jupyter labextension enable widgetslabextension
jupyter labextension enable python-markdown/main
jupyter labextension enable rise/main
jupyter labextension enable toc2/main
jupyter labextension enable ExecuteTime/main
jupyter labextension enable execute_time/ExecuteTime
jupyter labextension enable toggle_all_line_numbers/main
jupyter labextension enable varInspector/main
jupyter labextension enable codefolding/main
jupyter labextension enable exercise2/main
jupyter labextension enable code_prettify/code_prettify
jupyter labextension enable collapsible_headings/main
jupyter labextension enable equation-numbering/main

#jupyter nbextension install --sys-prefix --py nbgrader --overwrite
#jupyter nbextension enable --sys-prefix --py nbgrader
#jupyter serverextension enable --sys-prefix --py nbgrader
